export class RealtimeAudio{
 constructor({onInput=()=>{},onOutput=()=>{},onDrained=()=>{}}={}){this.onInput=onInput;this.onOutput=onOutput;this.onDrained=onDrained;this.sources=new Set();this.cursor=0;this.closed=false;this.generation=0;}
 async open(onPCM){
  this.ctx=new (globalThis.AudioContext||globalThis.webkitAudioContext)();await this.ctx.resume();
  this.output=this.ctx.createGain();this.output.connect(this.ctx.destination);this.analyser=this.ctx.createAnalyser();this.analyser.fftSize=256;this.output.connect(this.analyser);this.watchOutput();
  try{this.stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});await this.ctx.audioWorklet.addModule('/pcm-worklet.js');if(this.closed)return;
   this.mic=this.ctx.createMediaStreamSource(this.stream);this.recorder=new AudioWorkletNode(this.ctx,'pcm-recorder');this.silent=this.ctx.createGain();this.silent.gain.value=0;this.mic.connect(this.recorder);this.recorder.connect(this.silent);this.silent.connect(this.ctx.destination);
   this.recorder.port.onmessage=({data})=>{if(this.closed||this.muted){this.onInput(0);return;}const bytes=new Uint8Array(data),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let power=0;for(let i=0;i+1<bytes.length;i+=2)power+=(view.getInt16(i,true)/32768)**2;const rms=Math.sqrt(power/Math.max(1,bytes.length/2));this.onInput(rms<.008?0:Math.min(1,(rms-.008)*9));let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);onPCM(btoa(binary));};
  }catch(error){this.close();throw error;}
 }
 watchOutput(){const generation=this.generation,data=new Uint8Array(this.analyser.frequencyBinCount);const tick=()=>{if(this.closed||generation!==this.generation)return;this.analyser.getByteTimeDomainData(data);let power=0;for(const value of data)power+=((value-128)/128)**2;this.onOutput(Math.min(1,Math.sqrt(power/data.length)*3.6));this.frame=requestAnimationFrame(tick);};tick();}
 play(base64){if(this.closed||!this.ctx)return;const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0)),view=new DataView(bytes.buffer);const samples=new Float32Array(Math.floor(bytes.length/2));for(let i=0;i<samples.length;i++)samples[i]=view.getInt16(i*2,true)/32768;const buffer=this.ctx.createBuffer(1,samples.length,24000);buffer.copyToChannel(samples,0);const source=this.ctx.createBufferSource();source.buffer=buffer;source.connect(this.output);const start=Math.max(this.cursor,this.ctx.currentTime+.025);this.cursor=start+buffer.duration;source.start(start);this.sources.add(source);source.onended=()=>{this.sources.delete(source);if(!this.sources.size&&this.ctx.currentTime>=this.cursor-.08)this.onDrained();};}
 stop(){this.generation++;if(this.frame)cancelAnimationFrame(this.frame);for(const source of this.sources){try{source.stop();source.disconnect();}catch{}}this.sources.clear();this.cursor=this.ctx?.currentTime||0;this.onOutput(0);}
 mute(value){this.muted=value;this.stream?.getAudioTracks().forEach(track=>track.enabled=!value);if(value)this.onInput(0);}
 close(){if(this.closed)return;this.closed=true;this.stop();if(this.recorder)this.recorder.port.onmessage=null;this.stream?.getTracks().forEach(track=>track.stop());this.mic?.disconnect();this.recorder?.disconnect();this.silent?.disconnect();this.output?.disconnect();this.ctx?.close().catch(()=>{});this.onInput(0);}
}
